client profile and UI changes
Salesforce-org-Impact-Labs/01HousingandHomelessness pull request #282
Opened 2021-07-09 01:53 UTC by ShashiChettepu

1. Get Recommendations without profile builder
2. Batch job fix for "Email;Sms"
3. UI enhancements for refer "Mobile Phone Carrier"

# Critical Changes

# Changes

# Issues Closed

2021-07-13 18:36 UTC, anilpilakavv commented on force-app/main/default/classes/EmailService.cls
> +            map<id,Task> tskMap = new map<id,Task>();
What is the need of Map<Id, Task> in this use case? The list variable can be directly used instead of adding to a map.

2021-07-13 18:36 UTC, anilpilakavv commented on force-app/main/default/classes/getRecommendationsServiceQuery.cls
> +      //decimal age = calculateAge(client.Date_Of_Birth__c);
Remove commented code.

2021-07-13 18:38 UTC, anilpilakavv requested changes
Fix the review comments.

2021-07-15 15:52 UTC, ShashiChettepu commented on force-app/main/default/classes/EmailService.cls
> +            map<id,Task> tskMap = new map<id,Task>();
List will contain a duplicate id and running to the "System.ListException: Duplicate id in list error" 
https://salesforcescool.blogspot.com/2018/11/systemlistexception-duplicate-id-in.html?m=1

2021-07-15 16:16 UTC, anilpilakavv approved these changes

2021-07-15 17:50 UTC, ShashiChettepu commented
Merging to Master

2021-07-15 17:50 UTC, merged